* Title:
Particle Detectors and Anderson Localization: A "guide" to improving particle detection in scintillators

* Author list:
Kevin Keefe
Evan DeBlander
Ryan Dorril
John Learned
Kurtis Nishimura
Aline Tellez
David Welker

* Abstract:
We comment on recent progress in the use of Anderson Localization in the detection of optical photons. Anderson localization is a wave effect first used to describe the localized motion of an electron through a random potential.This effect has also been observed in optical photons that travel through a random two dimensional dielectric lattice potential, wherein the photons become localized along the direction transverse to the direction of disorder.Here we describe experiments done to qualitatively and quantitatively compare the effectiveness of localizing versus non-localizing scintillating material in their use as particle detectors. An experimental comparison between a prototype localizing scintillating material (a patented technology: "Nanoguide^tm", produced by Incom) and EJ200 isotropic scintillating material is discussed. Preliminary results between Nanoguide and EJ200 materials indicate a strong increase localization of the light. The coincidence timing between the silicon photomultiplier (SiPM) detector pixels for Nanoguide material has substantially increased compared to EJ200. This kind of two dimensional position resolution is not possible in other single bar uniform isotropic scintillators. Finally, we discuss possible applications of Nanoguide for new particle detectors.

