* Root files - store examples of root files which do various things
** Root histograms
*** Here are some examples of filling root histograms
**** hist 1
     utilizes a random fill of numbers.
     two different histograms are presented with different binning
**** hist 2
     an example of three histograms to compare random dice tosses
     the third histogram displays the frequency of the sum of the previous two dices
**** hist 3
     this is very similar to histogram 2, except at the end it spits out data onto the io stream and shows the entry #'s and counts
**** hist 4
     still open with current work to be done..

** Root graphs
*** Examples of root graphs. 
    Some examples of 1-D and N-D graphs are shown..
    Most common types unique to graphs:
    TF1 (or TFN) which describes the number of variables of a function..
    TCanvas - allows for multiple graphs to be placed on 
**** C1
     this is an example of a macro generated form the root canvas interface..
**** GraphTest.C
     first example of a self generated 1-D graph. 
     Very simple single graph template..
**** formula1.C
     this is an example using TCanvas to plot and display 3 different types of graphs..
     the third graph is a type TF2 which is a 2-variable function and plotted as such..

** Root functions
*** Fitting functions:
    these files all include different types of fitting and function
    
    examples that you can use as other temples
    
    //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......
    
**** graph 1

    this is the most basic kind of file graphing macro that you can use. all you would need to do is change the name of the graph file name, and it will graph the txt file assuming that the data is tab delineated.
    
    
    //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......
    
**** graph 2
    
    similar and simple graphing function but graphs a cube function of x from 0 to 10.
    
    //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......
    
**** graph 3
    
    this function graphs a set of random numbers for both x and y values
    
    this graph macro also introduces the following types of random functions:
    
    gRandom->Unifrom(double start, double finish); //this generates a random number between start and finish during each call.
    
    //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......
    
**** graph 4
    
    this is the example of a fit fitting function for a graph
    
    the main benefit of this macro is that you're able to use and create your own guess of a fitted function.
    
    you're capabale of defining the number of parameters to the fitted function.
    
    SetNames, defines the names of the parameters that you set in your TF1 guess fit.
    
    //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......

**** graph 5
    
    
    this is a slightly more complicated example of a fitted function than graph4.
    
    the guess function may have as many parameters to the guess that you would expect
    
    as a result, you can ALSO SET GUESS parameters to help increase the initial accuracy of the fit.

** Root General
   //in order to create a TFile use the following syntax:
   RECREATE is the option
   TFile *hfile = new TFile("nameof_file", "RECREATE", "Example");

** NTC specific root files and shell scrips
