#+TITLE: README

these files all include different types of fitting and function

examples that you can use as other temples

* graph 1

this is the most basic kind of file graphing macro that you can use. all you would need to do is change the name of the graph file name, and it will graph the txt file assuming that the data is tab delineated.


* graph 2

similar and simple graphing function but graphs a cube function of x from 0 to 10.

* graph 3

this function graphs a set of random numbers for both x and y values

this graph macro also introduces the following types of random functions:

gRandom->Unifrom(double start, double finish); //this generates a random number between start and finish during each call.

* graph 4

this is the example of a fit fitting function for a graph
the main benefit of this macro is that you're able to use and create your own guess of a fitted function.
you're capabale of defining the number of parameters to the fitted function.
SetNames, defines the names of the parameters that you set in your TF1 guess fit.

* graph 5
this is a slightly more complicated example of a fitted function than graph4.
the guess function may have as many parameters to the guess that you would expect
as a result, you can ALSO SET GUESS parameters to help increase the initial accuracy of the fit.
